### ISSUE TITLE
等式を解くことを試みる

### ISSUE THREAD

**Issue by kmyk** [kmyk/Jikka#126]
- [ ] 一般
  - [ ] 構文木として a と b が等しいなら `a == b` を `true` にする
- [ ] 整数について
  - [ ] 右辺を `0` にする。つまり `a == b` を `a - b == 0` にする
    - 両辺に分かれていたものがひとつの式になれば、別の最適化器 Jikka.Core.Convert.ArithmeticalExpr が頑張ってくれます
  - [ ] 組み込み関数 `f` であって[単射](https://ja.wikipedia.org/wiki/%E5%8D%98%E5%B0%84)なものについて `f(a) - f(b) == 0` を `a - b == 0` にする
- [ ] リストについて
  - [ ] `nil == cons(x, xs)` を `false` に
  - [ ] `cons(x, xs) == cons(y, ys)` を `x == y && xs == ys` に展開する
- [ ] 真偽値について
  - [ ] `a == true` を `a` に
  - [ ] `a == false` を `not a` に

**Comment by kmyk** [comment]
@hotman78

- すでに似たようなことをしている最適化器を丸ごとコピペして修正して動かすのがよさそう
- テストの実行方法などは [CONTRIBUTING.ja.md](https://github.com/kmyk/Jikka/blob/master/CONTRIBUTING.ja.md) にあります
- 両側が定数の場合のものは src/Jikka/Core/Convert/ConstantFolding.hs にあるので参考になりそう
- `a == b` という式の構文木は内部的には `Equal' t a b` という形ですが、この `t` には型が入っています

https://github.com/kmyk/Jikka/blob/13accbadd4aeb7ce49e76742a8f89fd960b0c261/src/Jikka/Core/Convert/ConstantFolding.hs#L182-L207

**Comment by hotman78** [comment]
ありがとうございます。
早速始めてみようと思います。
