### ISSUE TITLE
AtCoder ABC 200 - 212 の B 問題を examples/wip/ から examples/ に移す

### ISSUE THREAD

**Issue by kmyk** [kmyk/Jikka#150]
[uta8a/jikka-example](https://github.com/uta8a/jikka-example) からの https://github.com/kmyk/Jikka/pull/145 で @uta8a さんに足してもらったもの 

- [ ] `examples/wip/abc200_b.py`
- [x] `examples/wip/abc203_b.py`
- [x] `examples/wip/abc204_b.py`
- [x] `examples/wip/abc206_b.py`
- [x] `examples/wip/abc207_b.py`
- [x] `examples/wip/abc208_b.py`

手順は #141 にある
サンプルが合わないものについては先にバグ修正が必要。AC できるものはランダムケース生成器を書くことが必要

**Comment by kmyk** [comment]
@uta8a これやるの興味ないですか？ せっかくなのでお願いしたいです。WA なやつのデバッグはしんどいので、できそうなやつだけでも構いません

**Comment by uta8a** [comment]
了解です。やってみたいのでとりあえず手を付けてみます。

**Comment by kmyk** [comment]
ありがとう。お願いします

**Comment by kmyk** [comment]
連絡: #165 により `examples/wip/abc206_b.py` `examples/wip/abc208_b.py` が正しく動くようになったようです

**Comment by kmyk** [comment]
動いてない abc200_b は #173 があるので閉じてよい
(ありがとうございました)

**Comment by kmyk** [comment]
いや、#173 を解決した後に abc200_b を wip/ から外に出すの忘れそうだし open にしておこう
