### ISSUE TITLE
セグメント木や累積和に GCD や LCM を載せる

### ISSUE THREAD

**Issue by kmyk** [kmyk/Jikka#152]
いまは半群として (ℤ, +), (ℤ, min), (ℤ, max) しか使ってないけれど、gcd, lcm もほしい
特に <O(N), O(1)> GCD を貼れるとなんだかうれしい

**Comment by hotman78** [comment]
segment tree についてgcdは償却計算量となるのでそこまでうれしくはなさそうです、別のデータ構造として追加するのはとても賛成です

**Comment by hotman78** [comment]
LCMに関してはオーバーフローが大きな問題になりそうです

**Comment by hotman78** [comment]
> LCMに関してはオーバーフローが大きな問題になりそうですね...

とりあえずこの問題は無視して作ります
