### ISSUE TITLE
copy を move に直す際にやりすぎてる

### ISSUE THREAD

**Issue by kmyk** [kmyk/Jikka#154]
MoveSemantics.hs が以下のような C++ について

``` c++
int func(vector<int> a) {
    vector<int> b = a;
    b.push_back(10);
    vector<int> c = b;
    c.push_back(10);
    return b.size() + c.size();
}
```

これを間違えて

``` c++
int func(vector<int> a) {
    a.push_back(10);
    a.push_back(10);
    return a.size() + a.size();
}
```

に変換してるぽい

_Originally posted by @kmyk in https://github.com/kmyk/Jikka/issues/153#issuecomment-893423374_

**Comment by kmyk** [comment]
`push_back` が変数を更新することを考慮してない

**Comment by riantkb** [comment]
#153 #165 

新しい issue を立てるつもりでしたがここの話と同じような気がしてきたのでここに書きます。

```py
def f(n: int) -> int:
    a = 0
    b = 1
    for _ in range(n):
        c = (a + b) % 1000000007
        a = b
        b = c
    return a


def solve(n: int) -> int:
    return f(n)
```

上記のコードを変換した際に、`MoveSemantics` を __コメントアウトした__ 状態だと

```cpp
// ...
int64_t solve(int64_t n_0) {
    int64_t x1_4 = 1;
    int64_t x1_5 = 0;
    for (int32_t i2 = 0; i2 < int32_t(n_0); ++ i2) {
        int64_t x6 = jikka::mod::plus(jikka::modmat::floormod<2>(std::array<int64_t, 2>{x1_4, x1_5}, 1000000007)[1], jikka::modmat::floormod<2>(std::array<int64_t, 2>{x1_4, x1_5}, 1000000007)[0], 1000000007);
        int64_t x7 = x1_4;
        x1_4 = x6;
        x1_5 = x7;
    }
    return x1_5;
}
// ...
```

と正しいコードが得られるのに対し、 __コメントアウトしていない__ 状態だと

```cpp
// ...
int64_t solve(int64_t n_0) {
    int64_t x1_4 = 1;
    int64_t x1_5 = 0;
    for (int32_t i2 = 0; i2 < int32_t(n_0); ++ i2) {
        int64_t x6 = jikka::mod::plus(jikka::modmat::floormod<2>(std::array<int64_t, 2>{x1_4, x1_5}, 1000000007)[1], jikka::modmat::floormod<2>(std::array<int64_t, 2>{x1_4, x1_5}, 1000000007)[0], 1000000007);
        x1_4 = x6;
        x1_5 = x1_4;
    }
    return x1_5;
}
// ...
```

と正しくないコードが得られることを確認しました。

- version
  `$ git log --oneline -1`
  ```
  2edaccd Merge pull request #165 from riantkb/153-add-temporary-variable
  ```

**Comment by kmyk** [comment]
> たとえば
> 
> ```c++
> vector<int> func(vector<int> a) {
>     for (int i = 0; i < n - 1; ++ i) {
>         vector<int> b = a;
>         b[i + 1] = a[i];
>         a = b;
>     }
>     return a;
> }
> ```
> 
> を
> 
> ```c++
> vector<int> func(vector<int> a) {
>     for (int i = 0; i < n - 1; ++ i) {
>         a[i + 1] = a[i];
>     }
>     return a;
> }
> ```
> 
> に変換しないとだめなのだけど、これ無理じゃない？
> core から C++ への変換のときに情報が落ちてしまってて、その状態で添字の解析をやるのはしんどすぎるし、ある程度はやれたとしても不可能ケースが残ってしまう。
> UnpackTuples.hs や MoveSemantics.hs の中身をすべて ToCore.hs に埋め込んで、core から C++ への変換のときにすべてを同時に最適にやるしかなさそう

https://github.com/kmyk/Jikka/pull/168#issuecomment-894584836

実装方針ミスが発覚したときの顔をしています 😇

**Comment by riantkb** [comment]
確かに core 言語で書かれたコードを等価でない cpp に変換してから頑張る、というのはかなり筋が悪そうな気がするので、core を cpp に変換するタイミングで頑張るしかなさそうですね…… 😇
