### ISSUE TITLE
∑∑(aᵢ−aⱼ) で WA が出る

### ISSUE THREAD

**Issue by kmyk** [kmyk/Jikka#202]
## Summary / 概要

https://twitter.com/magrofly/status/1432932410321031172

@magurofly ありがとう

## Expected behavior / 期待される挙動

せめて TLE してほしい

## Actual behavior / 実際の挙動

WA するのはだめだろ

**Comment by kmyk** [comment]
これたすかる https://gist.github.com/magurofly/3ba197d58b9f95c6e804890095212e75

**Comment by riantkb** [comment]
C++ に詳しくないので知らなかったんですが、`std::accumulate` の返り値は第 3 引数 `__init` の方に一致するらしく、`(int64_t)0` にしてあげたら AC になりました
https://atcoder.jp/contests/abc186/submissions/25499595

**Comment by kmyk** [comment]
天才。私は式変形を疑ってばかりいました。

C++ のその仕様は知っていて accumulate を変換する時点ではちゃんと

https://github.com/kmyk/Jikka/blob/838de021c53dba2d7aadf30e411ea380a2868f65/src/Jikka/CPlusPlus/Convert/FromCore.hs#L367-L370

としてるのに、内部の構文木をコードに落とすところで余計なことをしていました:

https://github.com/kmyk/Jikka/blob/838de021c53dba2d7aadf30e411ea380a2868f65/src/Jikka/CPlusPlus/Format.hs#L199-L201

よければついでにプルリクもお願いしたい。せっかくデバッグ部分をやってもらったので
