### ISSUE TITLE
Python での list 操作の可能な範囲を広げる

### ISSUE THREAD

**Issue by kmyk** [kmyk/Jikka#56]
`xs.count()` とか `xs.append(x)` とかを書きたい。現在は Python パーサが method 呼び出しに対応していないので、そこから初める必要がある

**Comment by cannorin** [comment]
`a.b` をめちゃくちゃ高い優先度の binop として，`f(x)` をそれよりも高い優先度にするとうまくいくはず（あんまりよく覚えてない）

**Comment by kmyk** [comment]
xs.count(x) は書けるようになった。xs.append(x) は別 issue #73 へ
