### ISSUE TITLE
四則演算などの式を整理する

### ISSUE THREAD

**Issue by kmyk** [kmyk/Jikka#59]
`-1 + a + b - a + 2` が `b + 1` になってほしい
`Jikka.Core.Language.ArithmeticalExpr` をするだけなのだけど、局所的な書き換えでは済まないから rewrite rule には落ちなさそう

**Comment by cannorin** [comment]
これは float が絡むとめんどくさい（e.g. x = NaN のときに x - x を 0 にするのはまちがい）． GCC がよしなにしてくれるだろうし，そもそもする意味があるか不明かもしれない

**Comment by kmyk** [comment]
* float はそもそも存在してない (理由: 競プロで使う頻度が低い + まさにコメントしてもらったような理由で最適化が面倒) ので気にしなくて大丈夫です
* する意味はあるはず。式を整理することによってなにかがコンパイル時定数になるとうれしい (例: `let rec f n = if n == g(n) - g(n) then 1 else n * f(n - 1)` をループに直そうと思ったらまず `n == 0` に整理したい)

**Comment by cannorin** [comment]
素直に部分評価をかけるのがよいのではと思う．ただし副作用の扱いが面倒で，上の例だと `def g(n): return random.randint()` みたいなやつだと無理になる．純粋な関数かどうかをうまく判定してあげると楽かなと思う（このへんをちゃんとやろうとすると F* のような effect system が必要になる）
