### ISSUE TITLE
設計について

### ISSUE THREAD

**Issue by kmyk** [kmyk/Jikka#6]
現状 (`v3.1.0`)

1.  ML 風言語の構文解析をする
    -   lex + yacc で教科書通りにやった
1.  構文木を変形し最適化をする
    -   定数畳み込み (`x + 0` → `x` とか `if true then x else y` → `x` とか)
    -   大型演算子の分配 (`sum (fun i -> A i + B i)` → `sum (fun i -> A i) + sum (fun j -> B j)` とか)
    -   大型演算子の消去 (`max l r (fun i -> A i)` で `l` が定数のときに累積和に書き直すとか)
        -   このとき toplevel に新しい関数を追加することも
1.   C++ に変換する
     -    C++ は高級言語なのでいい感じにやるとできる

**Comment by kmyk** [comment]
最終的には、可能な式すべてのそれぞれを頂点、書き換え可能性の関係を辺、書き換える際に追加される前処理 (累積和とかセグ木とかの構築) の計算量を辺の重みとするグラフを作っていい感じに探索する、とかになると予想しています。

**Comment by yosupo06** [comment]
https://twitter.com/wata_orz/status/1282936222311014402 O(1)で計算できる問題だけですが、既存のものがあるのでなにかの参考になるかもしれません

**Comment by kmyk** [comment]
これすでに知ってた (たしか wata さん本人から教えてもらった) のだけど、すっかり忘れてたし、いまいちど読んでみたらわりと参考になることに気付きました。ありがとう。

ついでに: 先行研究としては kinaba さんのものもあります。こちらは実装はなくて構想のみなので歴史資料にしかならない (実装の参考にはならない) のですが、方向性はかなり近いです。
https://topcoder-g-hatena-ne-jp.jag-icpc.org/cafelier/20120204/1328332594.html
