### ISSUE TITLE
assert を core や C++ で利用する

### ISSUE THREAD

**Issue by kmyk** [kmyk/Jikka#65]
`assert n == len(a)` を利用して `map(lambda i: a[i], range(n))` を `a` に変換するなどしたい
いまは restricted Python → core の変換時に無視してしまってる

**Comment by cannorin** [comment]
Refinement Types っぽさがある

**Comment by kmyk** [comment]
わかる。
しかし refinement types がうれしいのは「複雑な事前条件/事後条件を型として表現できる」というユーザにとっての表現力のためであってコンパイラにとっての実装しやすさではないはずで、利用は見送りになりそうです。以前に教えてもらったときにやりかけたけど、型と項で相互再帰すると実装がとても面倒だったんですよね。

**Comment by cannorin** [comment]
アドホックにやるならとりあえず `assert <cond> in <body>` みたいな式に変換してあげて，optimizer が式を掘っていくときにそれに出会ったら `cond` を文脈の assertion 一覧に追加してあげてから `body` を処理するみたいな実装にすればなんとなく動きそう．
